language: java
sudo: false # faster builds

addons:
  sonarcloud:
    organization: "eninja-github"
    token:
      secure: $SONAR_TOKEN

script:
  - 'mvn cobertura:cobertura'
  - 'mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar'

after_success:
  - bash <(curl -s https://codecov.io/bash)